openapi: 3.0.3
info:
  title: Pharma Care API
  version: 1.0.0
  description: Public API for the Pharma Care company website.
paths:
  /api/blog-topics/:
    get:
      operationId: blog_topics_list
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - blog-topics
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBlogTopicList'
          description: ''
  /api/blogs/:
    get:
      operationId: blogs_list
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - blogs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBlogList'
          description: ''
  /api/blogs/{slug}/:
    get:
      operationId: blogs_retrieve
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - blogs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
          description: ''
  /api/categories/:
    get:
      operationId: categories_list
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCategoryList'
          description: ''
  /api/categories/{slug}/:
    get:
      operationId: categories_retrieve
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - categories
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
  /api/products/:
    get:
      operationId: products_list
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductList'
          description: ''
  /api/products/{slug}/:
    get:
      operationId: products_retrieve
      parameters:
      - in: query
        name: lang
        schema:
          type: string
        description: Response language. Use 'en' or 'ar'. Defaults to 'en'.
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
components:
  schemas:
    Blog:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          oneOf:
          - type: string
            maxLength: 255
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        topic:
          allOf:
          - $ref: '#/components/schemas/BlogTopicNested'
          readOnly: true
        title:
          type: string
          readOnly: true
        content:
          type: string
          readOnly: true
        image:
          type: string
          format: uri
          nullable: true
        published_at:
          type: string
          format: date-time
          nullable: true
      required:
      - content
      - id
      - title
      - topic
    BlogTopic:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          oneOf:
          - type: string
            maxLength: 255
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        name:
          type: string
          readOnly: true
        description:
          type: string
          readOnly: true
        icon:
          type: string
          format: uri
          nullable: true
      required:
      - description
      - id
      - name
    BlogTopicNested:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          oneOf:
          - type: string
            maxLength: 255
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        name:
          type: string
          readOnly: true
      required:
      - id
      - name
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          oneOf:
          - type: string
            maxLength: 255
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        name:
          type: string
          readOnly: true
        description:
          type: string
          readOnly: true
        image:
          type: string
          format: uri
          nullable: true
        display_order:
          type: integer
          maximum: 4294967295
          minimum: 0
          format: int64
      required:
      - description
      - id
      - name
    PaginatedBlogList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Blog'
    PaginatedBlogTopicList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/BlogTopic'
    PaginatedCategoryList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    PaginatedProductList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          oneOf:
          - type: string
            maxLength: 255
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        category:
          allOf:
          - $ref: '#/components/schemas/ProductCategory'
          readOnly: true
        name:
          type: string
          readOnly: true
        description:
          type: string
          readOnly: true
        image:
          type: string
          format: uri
          nullable: true
        display_order:
          type: integer
          maximum: 4294967295
          minimum: 0
          format: int64
        is_featured:
          type: boolean
        meta_title:
          type: string
          readOnly: true
        meta_description:
          type: string
          readOnly: true
      required:
      - category
      - description
      - id
      - meta_description
      - meta_title
      - name
    ProductCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        slug:
          oneOf:
          - type: string
            maxLength: 255
            pattern: ^[-a-zA-Z0-9_]+$
          - type: string
            maxLength: 0
        name:
          type: string
          readOnly: true
      required:
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
