/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScienceSlugRouteImport } from './routes/science_.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as ProductsCategorySlugRouteImport } from './routes/products_.category.$slug'
import { Route as ApiPharmaSplatRouteImport } from './routes/api.pharma.$'

const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceSlugRoute = ScienceSlugRouteImport.update({
  id: '/science_/$slug',
  path: '/science/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/products_/category/$slug',
  path: '/products/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPharmaSplatRoute = ApiPharmaSplatRouteImport.update({
  id: '/api/pharma/$',
  path: '/api/pharma/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/science': typeof ScienceRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/science/$slug': typeof ScienceSlugRoute
  '/api/pharma/$': typeof ApiPharmaSplatRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/science': typeof ScienceRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/science/$slug': typeof ScienceSlugRoute
  '/api/pharma/$': typeof ApiPharmaSplatRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/science': typeof ScienceRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/science_/$slug': typeof ScienceSlugRoute
  '/api/pharma/$': typeof ApiPharmaSplatRoute
  '/products_/category/$slug': typeof ProductsCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/products'
    | '/science'
    | '/products/$slug'
    | '/science/$slug'
    | '/api/pharma/$'
    | '/products/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/products'
    | '/science'
    | '/products/$slug'
    | '/science/$slug'
    | '/api/pharma/$'
    | '/products/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/products'
    | '/science'
    | '/products_/$slug'
    | '/science_/$slug'
    | '/api/pharma/$'
    | '/products_/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  ScienceRoute: typeof ScienceRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ScienceSlugRoute: typeof ScienceSlugRoute
  ApiPharmaSplatRoute: typeof ApiPharmaSplatRoute
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science_/$slug': {
      id: '/science_/$slug'
      path: '/science/$slug'
      fullPath: '/science/$slug'
      preLoaderRoute: typeof ScienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/category/$slug': {
      id: '/products_/category/$slug'
      path: '/products/category/$slug'
      fullPath: '/products/category/$slug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharma/$': {
      id: '/api/pharma/$'
      path: '/api/pharma/$'
      fullPath: '/api/pharma/$'
      preLoaderRoute: typeof ApiPharmaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  ScienceRoute: ScienceRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ScienceSlugRoute: ScienceSlugRoute,
  ApiPharmaSplatRoute: ApiPharmaSplatRoute,
  ProductsCategorySlugRoute: ProductsCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
